### ISSUE TITLE
FOR loop index is too large. Truncating to 9223372036854775807. 

### ISSUE THREAD

**Issue by ghost** [stephenbeckr/SparsifiedKMeans#3]
Hi!

I was using your sparsified kmeans and i think it is absolutely great. But i had encountered this error when using your code

Input: 5244949 x 35 in a mat file

Output: Splitting 5244949 x 35 matrix into Inf 5244949 x 0 chunks

The error code goes like this in matlab

`Warning: FOR loop index is too large. Truncating to 9223372036854775807. 
> In sampleAndMixFromLargeFile (line 96)
  In kmeans_sparsified (line 301)
  In example_loadFromDisk (line 55) 
Error using sampleAndMixFromLargeFile (line 100)
Cannot index into 'X' because indices cannot be empty.

Error in kmeans_sparsified (line 301)
        [X,timeLoad,timeMix,timeSample] = sampleAndMixFromLargeFile( DataFile, SparsityLevel, mix, p2,...

Error in example_loadFromDisk (line 55)
[indx,centers,sumd,dist_sketch] = kmeans_sparsified( [], k,'ColumnSamples',true,... '

I am using the loadfromDisk function but i've also tried using smaller values and it works like a charm.

**Comment by stephenbeckr** [comment]
Think there's some block-size issue, and it is setting the number of blocks to Infinity.  Can you tell me the values you are using for the parameters 'ColumnSamples' and 'MB_limit' ? Does it work if you change 'ColumnSamples' from false--> true (or vice-versa) and try adjusting MB_limit? And when it does work for smaller values, what matrix/parameters was that?

Also, the code is assuming you have 35 samples, each 5244949 dimensional, so it sounds to me like those are switched (you really have 5244949 samples, each 35 dimensional), which is what happens if 'ColumnSamples' isn't set right.

The actual bug is that my variable "nn" in private/sampleAndMixFromLargeFile.m is set to 0 (which can happen of MB_limit is very small, or the dataset is gigantic), so nBlocks=Inf. I've fixed it so that this won't happen (now nn>=1), but I think in your case there's something else going on that's worth investigating.

**Comment by ghost** [comment]
Hi!
Sorry for getting back at you so late. :) 

Yes i really have 5244949 samples each in 35 dimensions. so i changed ColumnSamples to false and changed the Mb_Limit to 1000. Which now worked fine. But as i run through my sample. I noticed that during the debugging phase that most of my returned output from the line 

```
if MLcorrection
                    centers(:,ki)   = SparsityLevel*full( sum(X(:,ind),2))./(full(sum(NormalizationMatrix(:,ind),2) )+1e-16);
```

always return a NaN value,  so i checked my samples and found that i really had NaN value in my samples so i changed the sum to nansum to ignore the Nan value in the kmeans_sparsified.m

```
if MLcorrection
                    centers(:,ki)   = SparsityLevel*full( nansum(X(:,ind),2))./(full(nansum(NormalizationMatrix(:,ind),2) )+1e-16);
```

Most of the "sum" in the .m file was changed to "nansum" to cater for my dataset.

The program now works and returns centers from the load disk. Cheers!

But is the warning really alright? the one with 
`
Warning: cluster has lost all its members 
> In kmeans_sparsified (line 433)
  In example_loadFromDisk (line 33) `

I noticed that the warning occurs several times as i run my dataset in your code.

Regards,
Albert Rey Ruelan

**Comment by stephenbeckr** [comment]
Hi Albert,
  That's a nice fix for the nan's in your dataset. I won't incorporate that into the code just yet, because it might be nice to throw the error and let people be aware of nan in their data (and if they want to ignore it, I can direct them to your fix).
  For the error about dropping clusters, that's a standard issue with all k-means, and it can often mean that you asked for too many clusters. I don't know of a great solution, but you can change the behavior by setting the 'EmptyAction' parameter to be 'singleton', and whenever a cluster has no members, the code will make a new cluster using the farthest-away point.
-Stephen
